GET http://localhost:8080/api

###

GET http://localhost:8080/api/posts

###

GET http://localhost:8080/api/posts/1

###

PUT http://localhost:8080/api/posts/1
Content-Type: application/json

// Put updated data here

{
	"username": "cameronape",
	"body": "dfsdfgsgdfxcvsdvsdf"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

// Put post data here

{
	"userId": 1,
	"body": "A third really cool post!"
}

###

DELETE http://localhost:8080/api/posts/3

###

GET http://localhost:8080/api/users

###

GET http://localhost:8080/api/users/1

###

GET http://localhost:8080/api/users/1/posts

###

PUT http://localhost:8080/api/users/5
Content-Type: application/json

// Put updated data here

{
	"username": "bigdaddy456",
	"password": "fuckinghumongouscock2"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

// Put post data here

{
	"username": "cameronape",
	"password": "password",
	"firstname": "cam",
	"lastname": "young",
	"role": "admin"
}

###

DELETE http://localhost:8080/api/users/3

###
