GET http://localhost:8080/api

###
GET http://localhost:8080/api/posts

###

GET http://localhost:8080/api/posts/1

###

PUT http://localhost:8080/api/posts/1
Content-Type: application/json

// Put updated data here

{
	"username": "cameronape",
	"body": "dfsdfgsgdfxcvsdvsdf"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

// Put post data here

{
	"username": "test user",
	"body": "Some really cool post!"
}

###

DELETE http://localhost:8080/api/posts/3